# Generated by Django 5.2.13 on 2026-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('duration', models.FloatField(default=2.0, verbose_name='游玩时间(小时)')),
                ('tags', models.CharField(max_length=200, verbose_name='兴趣标签')),
                ('rating', models.FloatField(default=4.0, verbose_name='评分')),
            ],
        ),
    ]
