# Generated by Django 5.2.13 on 2026-04-26 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='duration',
            field=models.FloatField(verbose_name='游玩时间(小时)'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
    ]
