# Generated by Django 5.2.13 on 2026-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_spot_duration_alter_spot_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.CharField(default='北京', max_length=50, verbose_name='所属城市'),
        ),
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='景点简介'),
        ),
        migrations.AddField(
            model_name='spot',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片链接'),
        ),
        migrations.AddField(
            model_name='spot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='门票价格(元)'),
        ),
    ]
