# Generated by Django 6.0.4 on 2026-05-03 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spot_address_spot_city_spot_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tip_type', models.CharField(choices=[('实用建议', '💡 实用建议'), ('避坑指南', '⚠️ 避坑指南'), ('美食推荐', '🍜 美食推荐'), ('交通攻略', '🚇 交通攻略'), ('拍照技巧', '📸 拍照技巧')], default='实用建议', max_length=20, verbose_name='类型')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.spot', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '景点攻略',
                'verbose_name_plural': '景点攻略',
                'ordering': ['-likes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='日记标题')),
                ('city', models.CharField(max_length=50, verbose_name='旅行城市')),
                ('content', models.TextField(verbose_name='日记内容')),
                ('mood', models.CharField(choices=[('开心', '😊 开心'), ('兴奋', '🤩 兴奋'), ('平静', '😌 平静'), ('感动', '🥹 感动'), ('疲惫', '😫 疲惫')], default='开心', max_length=20, verbose_name='心情')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='旅行评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '旅行日记',
                'verbose_name_plural': '旅行日记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.spot', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'spot')},
            },
        ),
    ]
