# Generated by Django 5.2.13 on 2026-05-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dashboardproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': '景点', 'verbose_name_plural': '景点'},
        ),
        migrations.AlterModelOptions(
            name='spottip',
            options={'ordering': ['-created_at'], 'verbose_name': '景点攻略', 'verbose_name_plural': '景点攻略'},
        ),
        migrations.RemoveField(
            model_name='spottip',
            name='likes',
        ),
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='行程名称')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('days', models.IntegerField(verbose_name='天数')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='兴趣标签')),
                ('budget', models.CharField(default='mid', max_length=20, verbose_name='预算等级')),
                ('plan_data', models.JSONField(verbose_name='行程数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '行程管理',
                'verbose_name_plural': '行程管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SavedTrip',
        ),
    ]
